# Generated by Django 5.1.7 on 2025-03-17 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("hotels", "0003_alter_hotel_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="hotel",
        ),
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hotels.room",
            ),
        ),
    ]
