version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: hotel
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "
      poetry run python manage.py migrate &&
      poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      IN_DOCKER: "True"
      POSTGRES_DB: hotel
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"


volumes:
  postgres_data:
