# Generated by Django 5.1.7 on 2025-03-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0002_hotel_address_hotel_city_room_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="name",
            field=models.CharField(default="Unnamed Hotel", max_length=255),
            preserve_default=False,
        ),
    ]
